### ISSUE TITLE
Migrate table IDs to larger datatype

### ISSUE THREAD

**Issue by ags** [ags/gendo#14]
Probably bigserial.
- [x] transactions
- [x] mailer_events
- [x] sql_events
- [x] view_events

**Comment by yesterdays-vigilante** [comment]
Since bigserial is just a bigint with a sequence on it (which rails appears to add itself), the type actually needs to be bigint (postgres actually won't let you alter to a bigserial anyway).

**Comment by ags** [comment]
Ah cool!
