### ISSUE TITLE
Consider a more generic model of events

### ISSUE THREAD

**Issue by ags** [ags/gendo#4]
Currently SQL, view and mailer events. May be possible to merge, but should that happen?

**Comment by yesterdays-vigilante** [comment]
Would be possibly nice for them to be linked together. Probably need to do that either through some kind of inheritance (I know STI isn't very nice [and neither is its acronym], but...) or to have some kind of symbolised 'type' field; I don't like this so much because it'll end up being very test-intensive (as in 'if' statements, not software tests!).

How were you thinking of doing it?

**Comment by ags** [comment]
Probably STI, but I don't really think it's a great idea, there's just a bit of duplication between event model fields. Behaviour isn't really an issue thanks to duck typing. I kind of expect the models to diverge anyway at some point.

**Comment by yesterdays-vigilante** [comment]
I actually kinda think STI would be good; we could just have a generic 'name' and 'body' field on each event and have an overridden method for processing etc. Realise that the superclass isn't strictly necessary, but it would make dealing with them _en masse_ a touch nicer.

**Comment by ags** [comment]
Yeah, I'm just not sure if it's an early optimisation - the models already have a few distinct fields, hard to tell where it's going and what's needed. The idea of a 'body' field is interesting for that data, but I whether it would be hard to query by their content at a large scale, not really a relational database thing - though postgres has hstore I guess. I wonder about the performance of one giant table too, when you have to filter by event type. Definitely worth keeping an eye on and experimenting with.

**Comment by yesterdays-vigilante** [comment]
I didn't think about performance implications; you raise a valid point. But with the right indexen, it shouldn't be a huge deal. I wasn't imagining querying by the body at all; if you're looking through that field in a relational database, there's probably a better way. I dunno, just thought it warranted further examination.
