### ISSUE TITLE
More insights

### ISSUE THREAD

**Issue by ags** [ags/gendo#5]
- [x] Sending emails in requests
- [x] Identifying n+1 queries
- [ ] Identify if gziping responses?

etc.

**Comment by yesterdays-vigilante** [comment]
How about stuff like
- [ ] Check for indexen on heavily-queried DB columns
- [ ] Identify where transactions/single-statement SQL should be used to improve speed of bulk inserts/updates

...?

**Comment by ags** [comment]
Good ideas, we should look into them further!

**Comment by yesterdays-vigilante** [comment]
If we were going to do the index thing, and even in general, it might be worth keeping a model of the schema of the client database (minus any redacted tables). Not sure if this is ethical.

**Comment by ags** [comment]
You'd have to know when to send it though, it'd be annoying to send with every request. There's the [index_exists?](http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/index_exists%3F) method, which might be useful, but you have to know which columns to check, which suggests a way of communicating between gendo and shinji, not just shinji to gendo. That might be even less ethical :p

**Comment by yesterdays-vigilante** [comment]
I guess you could just send the schema with each deploy. There doesn't appear to be before or after migrate hooks, alas. Though, this is Ruby. We could just make them ourselves.

**Comment by ags** [comment]
If you associated a github repo with an app, it ought to be possible to retrieve the schema whenever. Then you have to deal with differences in schema.rb vs structure.sql for different DBs. Also somewhat restricted to github and additional setup, but could be handy for non core features, like showing you where in your code a slow thing is.

**Comment by ags** [comment]
Distinct issues created (#23 & #24).
